package au.lyrael.needsmoredragons.utility;

import cpw.mods.fml.common.ModMetadata;
import au.lyrael.needsmoredragons.NeedsMoreDragons;

public class MetadataHelper {
    public static ModMetadata transformMetadata(ModMetadata meta) {
        meta.authorList.clear();
        meta.authorList.add("LyraelRayne");
        meta.modId = NeedsMoreDragons.MOD_ID;
        meta.name = NeedsMoreDragons.MOD_NAME;
        meta.version = NeedsMoreDragons.VERSION;
        meta.description = NeedsMoreDragons.DESC;
        meta.url = NeedsMoreDragons.URL;
        meta.credits = NeedsMoreDragons.CREDITS;
        meta.logoFile = NeedsMoreDragons.LOGO_PATH;
        meta.autogenerated = false;
        return meta;
    }
}
